### ISSUE TITLE
Support 2.13

### ISSUE THREAD

**Issue by markus1189** [47deg/scalacheck-toolbox#63]
We are unfortunately blocked by this to upgrade to 2.13.  When is a 2.13 release planned?

I did some work on the `sbt-org-policies` project as well to support 2.13:
- https://github.com/47deg/sbt-org-policies/pull/1190
- https://github.com/47deg/sbt-org-policies/pull/1189

Afterwards I would hope that `scalacheck-toolbox` could be released as well

**Comment by reibitto** [comment]
I see that both of the referenced issues have been merged. Is there anything else needed for this? Just wondering.

**Comment by juanpedromoreno** [comment]
Thanks @reibitto , thanks for the reminder. Yeah, hopefully, this library is supporting Scala 2.13 today: https://github.com/47deg/scalacheck-toolbox/pull/68

**Comment by juanpedromoreno** [comment]
`scalacheck-toolbox` 0.3.1 is out now, supporting Scala 2.13 :)
